### ISSUE TITLE
using "bdesk_photo" and "past" conflict

### ISSUE THREAD

**Issue by mikecastrodemaria** [buddyexpress/bdesk_photo#1]
Thank for this plugin, I test it on tinymce 4.1.5, but if you are using "past" plugin, it not work.

You can see the button, open the dialog for select image, but no img tag inserted. Without "past" plugin, it work like a charm. Any idea ?

Thanks

**Comment by lianglee** [comment]
Hmm no idea, i will check it , if you need quick fix you can post on stackoverflow.com along with this project url.

Thanks

**Comment by cafealternativo** [comment]
tinymce was stripping the base64 node, so nothing was being inserted. . If you are experiencing this problem make the following modifications.

1- The insertContent command parses the node and deletes the content. Even mceInsertRawHTML doesn't work because it has the raw parameter turned off, so we need a new command.
 After the addButton sentence add the following command to tinymce.

//---------------------------  
<code>
    editor.addCommand("trueInsertRawHTML", function (value) {  
        this.selection.setContent('tiny_mce_marker');
        editor.setContent(
            editor.getContent().replace(/tiny_mce_marker/g, function () {
                return value;
            }), { format: "raw" }
        );
    });
</code>
//-------------------

2- Replace this line:
<code>
editor.execCommand("mceInsertContent", false, "<img src='" + imgData + "' />");
</code>
With:
<code>
editor.execCommand("trueInsertRawHTML", "<img src='" + imgData + "' />");
</code>
Hope this helps the next customer...

**Comment by lianglee** [comment]
Fixed thanks

**Comment by cafealternativo** [comment]
You forgot to add the command.

**Comment by lianglee** [comment]
Can you send us pull request? go to the file in our repository and click edit, after changes save and click on send pull request.

**Comment by cafealternativo** [comment]
Ok will do. Im having a problem with tiny mce after the content is embbeded. Now I think it has something to do with a tinymce option. After I have everything figured out, Ill add any changes if needed.
Regards.

Date: Tue, 7 Apr 2015 08:29:51 -0700

**Comment by cafealternativo** [comment]
I added the changes. 
I want to add that tinyMCE will strip out all base64 content. It has to do with a eager regular expression and the content ending with "=" .

The only way to support the base64 content is to set the html as raw.

## You can add this to your init method:

init_instance_callback : function() { 

```
            tinyMCE.activeEditor.setContent($("#contentId").html, { format: "raw" });

        }
```
