### ISSUE TITLE
TinyMCE 4 strips img tags with base64

### ISSUE THREAD

**Issue by Fmstrat** [buddyexpress/bdesk_photo#2]
I'm still trying to figure out how to fix this myself, but the instructions should be updated once this is resolved.

**Comment by lianglee** [comment]
Actually this plugin automatically convert img to base64

**Comment by cafealternativo** [comment]
tinymce was stripping the base64 node, so nothing was being inserted. . If you are experiencing this problem make the following modifications.

1- The insertContent command parses the node and deletes the content. Even mceInsertRawHTML doesn't work because it has the raw parameter turned off, so we need a new command.
 After the addButton sentence add the following command to tinymce.

//---------------------------  
    editor.addCommand("trueInsertRawHTML", function (value) {  
        this.selection.setContent('tiny_mce_marker');
        editor.setContent(
            editor.getContent().replace(/tiny_mce_marker/g, function () {
                return value;
            }), { format: "raw" }
        );
    });
//-------------------

2- Replace this line:

editor.execCommand("mceInsertContent", false, "<img src='" + imgData + "' />");

With:

editor.execCommand("trueInsertRawHTML", "<img src='" + imgData + "' />");

Hope this helps the next customer...

**Comment by lianglee** [comment]
Fixed thanks

**Comment by nathancarter** [comment]
I created a TinyMCE bug report for this.  Vote for it here:
http://www.tinymce.com/develop/bugtracker_view.php?id=7549

**Comment by nathancarter** [comment]
Actually, the solution for this is a tiny tweak to your TinyMCE configuration.  See here:
http://stackoverflow.com/a/30767277/670492

**Comment by xaviergonz** [comment]
and you can use this in your tinymce 4 init script so your images are really saved as base64 (even pasted ones)

``` javascript
    paste_data_images: true,
    images_upload_handler: function (blobInfo, success, failure) {
      // no upload, just return the blobInfo.blob() as base64 data
      success("data:" + blobInfo.blob().type + ";base64," + blobInfo.base64());
    }
```

PS: with this code you don't need to change mceInsertContent, it will work

**Comment by lianglee** [comment]
@xaviergonz , can you send pull request? or send us complete file with changes, we shall update it.

Thanks

**Comment by xaviergonz** [comment]
How would I? The code needs to be added to the tinymce.init() function, not to your plugin itself.

**Comment by lianglee** [comment]
@xaviergonz ok thanks :+1:

**Comment by xaviergonz** [comment]
I did create a pull request based on the code I use, but it is quite a big pull request :)
It does work in tinymce 4 latest version (tested), however I did not test it with v3.

**Comment by zkozma** [comment]
Thx xaviergonz! The images_upload_handler is working!

**Comment by syedzahed** [comment]
@xaviergonz Thanks
